apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "url-shortener.fullname" . }}-config

data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  DYNAMODB_TABLE: {{ .Values.config.dynamodbTable | quote }}
